name: Release
on:
  release:
    types: [created]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # Remove development files
      - name: Clean-up project
        uses: PrestaShopCorp/github-action-clean-before-deploy@v1.0

      # Zip files and upload to artifacts list
      - name: Create & upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ github.event.repository.name }}
          path: ${{ github.workspace }}
